# Generated by Django 6.0.7 on 2026-09-09 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('users', '0002_action_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='catalogo.negocio'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='slug_publico',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='zona_horaria',
            field=models.CharField(default='America/La_Paz', max_length=80),
        ),
    ]
