# Generated by Django 6.0.7 on 2026-09-09 02:12

import catalogo.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_action_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('descripcion_publica', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('correo_publico', models.EmailField(blank=True, max_length=254)),
                ('logo_url', models.URLField(blank=True)),
                ('portada_url', models.URLField(blank=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos')], default='BOB', max_length=3)),
                ('publicado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion_publica', models.TextField(blank=True)),
                ('superficie', models.CharField(blank=True, max_length=100)),
                ('techada', models.BooleanField(default=False)),
                ('iluminacion', models.BooleanField(default=False)),
                ('capacidad_personas', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('anticipacion_minutos', models.PositiveIntegerField(default=0)),
                ('duracion_minima_minutos', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('activa', models.BooleanField(default=True)),
                ('publicada', models.BooleanField(default=False)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canchas', to='users.sucursal')),
            ],
            options={
                'ordering': ['sucursal_id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CanchaDeporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deportes', to='catalogo.cancha')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='FotoCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo', models.ImageField(upload_to=catalogo.models.photo_path)),
                ('texto_alternativo', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('publicada', models.BooleanField(default=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos', to='catalogo.cancha')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HorarioCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
                ('cruza_medianoche', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='catalogo.cancha')),
            ],
            options={
                'ordering': ['dia_semana', 'apertura'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('horas_limite_cancelacion', models.PositiveIntegerField(default=5)),
                ('porcentaje_anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minutos_retencion', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('condiciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='politicas', to='users.sucursal')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TarifaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('dia_semana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('cruza_medianoche', models.BooleanField(default=False)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('activa', models.BooleanField(default=True)),
                ('cancha_deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='catalogo.canchadeporte')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_desde', 'vigente_desde'],
            },
        ),
        migrations.AddConstraint(
            model_name='cancha',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='cancha_codigo_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='cancha',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_minima_minutos__gt', 0)), name='cancha_minimo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='canchadeporte',
            constraint=models.UniqueConstraint(fields=('cancha', 'deporte'), name='cancha_deporte_unico'),
        ),
        migrations.AddConstraint(
            model_name='horariocancha',
            constraint=models.CheckConstraint(condition=models.Q(('dia_semana__range', (1, 7))), name='horario_dia_valido'),
        ),
        migrations.AddConstraint(
            model_name='politicareserva',
            constraint=models.UniqueConstraint(fields=('sucursal', 'version'), name='politica_version_unica'),
        ),
        migrations.AddConstraint(
            model_name='tarifacancha',
            constraint=models.CheckConstraint(condition=models.Q(('precio_hora__gt', 0)), name='tarifa_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='tarifacancha',
            constraint=models.CheckConstraint(condition=models.Q(('dia_semana__range', (1, 7))), name='tarifa_dia_valido'),
        ),
    ]
