# Generated by Django 6.0.7 on 2026-09-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial_catalog'),
        ('users', '0003_sucursal_latitud_sucursal_longitud_sucursal_negocio_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='horariocancha',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cierre__gt', models.F('apertura')), ('cruza_medianoche', False)), models.Q(('cierre__lte', models.F('apertura')), ('cruza_medianoche', True)), _connector='OR'), name='horario_intervalo_valido'),
        ),
        migrations.AddConstraint(
            model_name='politicareserva',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_anticipo__isnull', True), models.Q(('porcentaje_anticipo__gt', 0), ('porcentaje_anticipo__lte', 100)), _connector='OR'), name='politica_anticipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='tarifacancha',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cruza_medianoche', False), ('hora_hasta__gt', models.F('hora_desde'))), models.Q(('cruza_medianoche', True), ('hora_hasta__lte', models.F('hora_desde'))), _connector='OR'), name='tarifa_intervalo_valido'),
        ),
        migrations.AddConstraint(
            model_name='tarifacancha',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gte', models.F('vigente_desde')), _connector='OR'), name='tarifa_vigencia_valida'),
        ),
    ]
